var res = {
    XiaoWu_jpg : "res/xiaowu.jpg",
    blue_ciyu_png : "res/blue_ciyu.png",
    blue_duanzi_png : "res/blue_duanzi.png",
    blue_juzi_png : "res/blue_juzi.png",
    blue_wenzhang_png : "res/blue_wenzhang.png",
    red_ciyu_png : "res/red_ciyu.png",
    red_duanzi_png : "res/red_duanzi.png",
    red_juzi_png : "res/red_juzi.png",
    red_wenzhang_png : "res/red_wenzhang.png",
    jiantou_png : "res/jiantou.png",
    blue_animal_png : "res/blue_animal.png",
    blue_city_png : "res/blue_city.png",
    blue_plant_png : "res/blue_plant.png",
    blue_subway_png : "res/blue_subway.png",
    blue_vihicle_png : "res/blue_vihicle",
    red_animal_png : "res/red_animal.png",
    red_city_png : "res/red_city.png",
    red_plant_png : "res/red_plant.png",
    red_subway_png : "res/red_subway",
    red_vihicle_png : "res/red_vihicle.png",
    one_blue_png : "res/one_blue.png",
    one_red_png : "res/one_red.png",
    play_png : "res/play.png",
    jiantou_red_png : "res/jiantou_red.png",
    play_red_png : "res/play_red.png",
    red_car_png : "res/car_red.png",
    blue_car_png : "res/car_blue.png",
    set_png : "res/settings.png",
    dialog_png : "res/dialog.png",
    stop_png : "res/stop.png",
    zibian_blue_png : "res/zibian_blue.png",
    zibian_red_png : "res/zibian_red.png",
    add_blue_png : "res/add.png",
    content_frame_png : "res/contentFrame.png",
    save_blue_png : "res/save_blue.png",
    save_red_png : "res/save_red.png",
    blue_frame_png : "res/blue_frame.png",
    red_frame_png : "res/red_frame.png",
    trim_png : "res/trim.png",
    logo_png : "res/logo.png",
    hello_png : "res/HelloWorld.png"
};

var g_resources = [];
for (var i in res) {
    g_resources.push(res[i]);
}